import { useState } from "react";

export function AdminStudio({ artists, onClose, onCreateArtist, onCreateTrack }) {
  const [artist, setArtist] = useState({ name: "", bio: "", image: "" });
  const [track, setTrack] = useState({ title: "", artist: "", genre: "Pop", duration: "", isPremium: false, audio: null, cover: null });
  const submitArtist = async event => { event.preventDefault(); await onCreateArtist(artist); setArtist({ name: "", bio: "", image: "" }); };
  const submitTrack = async event => { event.preventDefault(); await onCreateTrack(track); setTrack({ title: "", artist: "", genre: "Pop", duration: "", isPremium: false, audio: null, cover: null }); };
  return <div className="modal admin"><div><button className="close" onClick={onClose}>×</button><h2>Admin studio</h2><p>Artist and track publishing are restricted to administrators.</p><h3>Create artist</h3><form onSubmit={submitArtist}><input required placeholder="Artist name" value={artist.name} onChange={event => setArtist({ ...artist, name: event.target.value })} /><input placeholder="Image URL" value={artist.image} onChange={event => setArtist({ ...artist, image: event.target.value })} /><input placeholder="Short bio" value={artist.bio} onChange={event => setArtist({ ...artist, bio: event.target.value })} /><button>Add artist</button></form><div className="artist-list">{artists.map(item => <span key={item._id}>{item.name} {item.verified && "✓"}</span>)}</div><h3>Publish track</h3><form onSubmit={submitTrack}><input required placeholder="Track title" value={track.title} onChange={event => setTrack({ ...track, title: event.target.value })} /><select required value={track.artist} onChange={event => setTrack({ ...track, artist: event.target.value })}><option value="">Choose artist</option>{artists.map(item => <option key={item._id} value={item._id}>{item.name}</option>)}</select><select value={track.genre} onChange={event => setTrack({ ...track, genre: event.target.value })}><option>Pop</option><option>Electronic</option><option>Lo-fi</option><option>Indie</option><option>R&amp;B</option><option>Hip-Hop</option><option>House</option><option>Acoustic</option><option>Ambient</option><option>Rock</option></select><input type="number" min="0" placeholder="Duration in seconds" value={track.duration} onChange={event => setTrack({ ...track, duration: event.target.value })} /><label>Audio file<input required type="file" accept="audio/*" onChange={event => setTrack({ ...track, audio: event.target.files[0] })} /></label><label>Cover image (optional)<input type="file" accept="image/*" onChange={event => setTrack({ ...track, cover: event.target.files[0] })} /></label><label className="check"><input type="checkbox" checked={track.isPremium} onChange={event => setTrack({ ...track, isPremium: event.target.checked })} />Premium-only track</label><button>Publish track</button></form></div></div>;
}
